app_membre/urls.py
from django.urls import path
from . import views

app_name = 'app_membre'

urlpatterns = [
    path('', views.member_home, name='home_membre'),
    path('liste_medias_membre/', views.list_medias_member, name='liste_medias_membre'),
]

my_mediatheque_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'), # Page d'accueil générale
    path('bibliothecaire/', include('app_bibliothecaire.urls'), name='bibliothecaire'), #Page d'accueil pour les bibliothécaires
    path('membre/', include('app_membre.urls'), name='membre'), #Page d'accueil pour les membres
    path('login/', auth_views.LoginView.as_view(template_name='app_biblio/login.html'), name='login'), # Page de connexion
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), # Page de déconnexion de l'utilisateur
]

app_membre/models.py
from django.db import models

# Create your models here.

app_membre/views.py
from django.shortcuts import render
from app_bibliothecaire.models import Book, Dvd, Cd, Board


def member_home(request):
    return render(request, 'app_memb/home_membre.html')


def list_medias_member(request):
    # Recharge les médias depuis la BDD pour afficher l'état actuel
    books = Book.objects.all()
    dvds = Dvd.objects.all()
    cds = Cd.objects.all()
    boards = Board.objects.all()

    # Permet la prise en compte d'un emprunt en cours
    for book in books:
        book.current_loans = book.loans.filter(effective_return_date__isnull=True).first()
    for dvd in dvds:
        dvd.current_loans = dvd.loans.filter(effective_return_date__isnull=True).first()
    for cd in cds:
        cd.current_loans = cd.loans.filter(effective_return_date__isnull=True).first()

    context = {
        'books': books,
        'dvds': dvds,
        'cds': cds,
        'boards': boards,
    }
    return render(request, 'app_memb/liste_medias_membre.html', context)

app_membre/templates/app_memb/home_membre.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Membre - Accueil</title>
</head>
<body>
    <h1>Bienvenue sur la page d'accueil des membres !</h1>
    <a href="{% url 'app_membre:liste_medias_membre' %}">Accéder à la liste des médias</a><br><br>
    <button>
      <a href="{% url 'home' %}">Retour au menu principal</a>
    </button>
</body>
</html>

app_membre/templates/app_memb/liste_medias_membre.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Liste des Médias - Membre</title>
</head>
<body>
    <a href="{% url 'app_membre:home_membre' %}">Retour au menu</a>
    <h1>Liste des Médias</h1>

    <h2>Livres</h2>
    <ul>
        {% for book in books %}
        <li>
          <p>Titre : {{ book.name }}</p>
          <p>Auteur : {{ book.author }}</p>
          <p>Nombre de pages : {{ book.nb_pages }}</p>
          {% if book.current_loans %}
            <p style="color:red;">Média déjà en cours d'emprunt</p>
          {% else %}
            <p>Disponible à l'emprunt</p>
          {% endif %}
        </li><br>
        {% endfor %}
    </ul>

    <h2>DVD</h2>
    <ul>
        {% for dvd in dvds %}
        <li>
          <p>Titre : {{ dvd.name }}</p>
          <p>Réalisateur : {{ dvd.author }}</p>
          <p>Genre : {{ dvd.genre }}</p>
          {% if dvd.current_loans %}
            <p style="color:red;">Média déjà est cours d'emprunt</p>
          {% else %}
            <p>Disponible à l'emprunt</p>
          {% endif %}
        </li><br>
        {% endfor %}
    </ul>

    <h2>CD</h2>
    <ul>
        {% for cd in cds %}
        <li>
          <p>Titre : {{ cd.name }}</p>
          <p>Artiste : {{ cd.author }}</p>
          <p>Date de sortie : {{ cd.release_date }}</p>
          {% if cd.current_loans %}
            <p style="color:red;">Média déjà en cours d'emprunt</p>
          {% else %}
            <p>Disponible à l'emprunt</p>
          {% endif %}
        </li><br>
        {% endfor %}
    </ul>

    <h2>Jeux de plateau</h2>
    <ul>
        {% for board in boards %}
        <li>
          <p>Nom du jeu : {{ board.name }}</p>
          <p>Créateur : {{ board.author }}</p>
          <p>Nombre de joueurs : de {{ board.number_players_min }} à {{ board.number_players_max}} joueurs</p>
          <p style="color: red; font-weight: bold;">Les jeux de plateaux ne sont pas disponibles à l'emprunt.</p>
        </li><br>
        {% endfor %}
    </ul>

</body>
</html>