app_bibliothecaire/urls.py
from django.urls import path
from . import views

app_name = 'app_bibliothecaire'

urlpatterns = [
    path('', views.home_librarian, name='home_bibliothecaire'),
    path('listmembres/', views.listmembers, name='listmembres'),
    path('ajoutmembre/', views.addmember, name='ajoutmembre'),
    path('updatemembre/<int:id>/', views.memberupdate, name='updatemembre'),
    path('deletemembre/<int:id>/', views.memberdelete, name='deletemembre'),
    path('listmedia/', views.listmedia, name='listmedia'),
    path('ajoutmedia/', views.addmedia, name='ajoutmedia'),
    path('ajout_livre/', views.add_book, name='ajout_livre'),
    path('ajout_dvd/', views.add_dvd, name='ajout_dvd'),
    path('ajout_cd/', views.add_cd, name='ajout_cd'),
    path('ajout_plateau/', views.add_board, name='ajout_plateau'),
    path('creer_emprunt/', views.create_loan, name='creer_emprunt'),
    path('retour_emprunt/', views.return_loan, name='retour_emprunt'),
    path('deletemedia/<int:id>/', views.mediadelete, name='deletemedia'),
]

app_membre/urls.py
from django.urls import path
from . import views

app_name = 'app_membre'

urlpatterns = [
    path('', views.member_home, name='home_membre'),
    path('liste_medias_membre/', views.list_medias_member, name='liste_medias_membre'),
]

my_mediatheque_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'), # Page d'accueil générale
    path('bibliothecaire/', include('app_bibliothecaire.urls'), name='bibliothecaire'), #Page d'accueil pour les bibliothécaires
    path('membre/', include('app_membre.urls'), name='membre'), #Page d'accueil pour les membres
    path('login/', auth_views.LoginView.as_view(template_name='app_biblio/login.html'), name='login'), # Page de connexion
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), # Page de déconnexion de l'utilisateur
]

app_bibliothecaire/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta


class Member(models.Model):
    """ Modèle de base d'un Membre.
    Attributs :
        name (str) : Nom du membre.
        first_name (str) : Prénom du membre.
        email (str) : Adresse email du membre (facultatif).
        phone (str) : Numéro de téléphone du membre (facultatif).
        creation_date (datetime) : Date de création du compte du membre.
    """
    name = models.fields.CharField(max_length=150)
    first_name = models.fields.CharField(max_length=150)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    creation_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        """ Retourne une représentation textuelle de l'objet.
        Exemple : "Doe John"
        """
        return f"{self.name} {self.first_name}"


class Media(models.Model):
    """ Modèle de base d'un Média.
    Attributs :
        name (str) : Nom du média.
        author (str) : Auteur ou créateur du média.
        category (str) : Catégorie du média (choix parmi 'livre', 'dvd', 'cd', 'plateau').
        availability (bool) : Indique si le média est disponible pour l'emprunt.
        borrower (Member) : Référence vers le membre ayant emprunté ce média.
        loan_date (datetime) : Date de l'emprunt.
    """

    CATEGORY_CHOICES = [
        ('book', 'Book'),
        ('dvd', 'Dvd'),
        ('cd', 'Cd'),
        ('board', 'Board'),
    ]
    name = models.fields.CharField(max_length=150)
    author = models.fields.CharField(max_length=250)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, default='book')
    availability = models.BooleanField(default=True)
    borrower = models.ForeignKey(Member, null=True, blank=True, on_delete=models.SET_NULL)
    loan_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name


class Book(Media):
    """ Modèle de base d'un livre.
    Attributs supplémentaires :
        nb_pages (int) : Nombre de pages du livre.
    """
    nb_pages = models.IntegerField(null=True, blank=True)


class Dvd(Media):
    genre = models.fields.CharField(max_length=250, null=True, blank=True)


class Cd(Media):
    release_date = models.DateField(null=True, blank=True)


class Board(Media):
    number_players_min = models.IntegerField(null=True, blank=True)
    number_players_max = models.IntegerField(null=True, blank=True)


def get_default_loan_date():
    # Calcule la date de retour prévue en fonction de la date d'emprunt
    return timezone.now().date() + timedelta(days=7)


class Loan(models.Model):
    """ Modèle de base de l'emprunt d'un média par un membre.
    Attributs :
        borrower (Member) : Référence vers le membre qui emprunte.
        media (Media) : Référence vers le média emprunté.
        loan_date (datetime) : Date de l'emprunt.
        expected_return_date (date) : Date prévue pour le retour.
        effective_return_date (date) : Date réelle du retour.
    """
    borrower = models.ForeignKey(
        Member,
        on_delete=models.CASCADE,
        related_name="loans"
    )
    media = models.ForeignKey(
        Media,
        on_delete=models.CASCADE,
        related_name="loans"
    )
    loan_date = models.DateTimeField(null=True, blank=True)
    expected_return_date = models.DateField(default=get_default_loan_date)
    effective_return_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.media.name} emprunté par {self.borrower}"

    def check_borrowing_limit(self):
        """ Vérifie si le membre a atteint la limite de 3 emprunts actifs
        et
        lève une exception ValueError si la limite est atteinte.
        """
        active_loans = Loan.objects.filter(
            borrower=self.borrower,
            effective_return_date__isnull=True
        ).count()
        if active_loans >= 3:
            raise ValueError(f"{self.borrower} a déjà 3 emprunts actifs")

    def check_late_loans(self):
        """ Vérifie si le membre a des emprunts en retard
        et
        lève une exception ValueError si un retard est détecté.
        """
        late_loans = Loan.objects.filter(
            borrower=self.borrower,
            effective_return_date__isnull=True,
            expected_return_date__lt=timezone.now().date()
        )
        if late_loans.exists():
            raise ValueError(
                f"{self.borrower} a des emprunts en retard et ne peut paas emprunter de nouveaux médias.")

    def check_availability_media(self):
        if not self.media.availability:
            raise ValueError(f"{self.media.name} n'est pas disponible à l'emprunt.")

    def mark_media_as_available(self):
        self.media.availability = True
        self.media.save()

    def mark_media_as_unavailable(self):
        self.media.availability = False
        self.media.save()

    def save(self, *args, **kwargs):
        """ Save applique les règles de validation avant l'enregistrement :
                - Vérifie les emprunts en cours.
                - Vérifie la disponibilité du média.
                - Marque le média comme non disponible si l'emprunt est actif.
        """
        if self.effective_return_date:
            self.mark_media_as_available()
        else:
            self.check_availability_media()
            self.check_borrowing_limit()
            self.check_late_loans()
            if not self.loan_date:
                self.loan_date = timezone.now().date()
            if not self.expected_return_date:
                self.expected_return_date = self.loan_date + timedelta(days=7)
            self.mark_media_as_unavailable()
        super().save(*args, **kwargs)

app_bibliothecaire/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from app_bibliothecaire.models import Member, Book, Dvd, Cd, Board, Loan, Media
from app_bibliothecaire.forms import (Membercreation, Memberupdate, BookForm, DvdForm,
                                      CdForm, BoardForm, LoanForm, SelectBorrowerForm, ReturnLoanForm)
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import timedelta
import logging

# Création du logger
logger = logging.getLogger(__name__)


# Fonctionnalité : Menu principal
@login_required
def home_librarian(request):
    logger.info("Accès à la page d'accueil du bibliothécaire.")
    return render(request, 'app_biblio/home_bibliothecaire.html')


# Fonctionnalités : Membre
def listmembers(request):
    """ Affiche la liste des membres.
        Pour chaque membre, récupère les emprunts en cours et les inclut dans l'objet membre.
        En cas d'erreur, une redirection vers la page d'accueil est effectuée avec un message.

        Paramètres :
            - request (HttpRequest) : L'objet requête HTTP.

        Retour :
            - HttpResponse : Rendu de la page 'membres/listmembres.html' avec le contexte :
                - membres (QuerySet) : Liste des membres et leurs emprunts.
            - HttpResponseRedirect : Redirection vers la page d'accueil en cas d'erreur.
        """
    logger.info("Accès à la liste des membres.")
    try:
        members = Member.objects.all()
        for member in members:
            member.current_loans = Loan.objects.filter(borrower=member, effective_return_date__isnull=True)
            logger.debug(f"{len(members)} membres récupérés.")
            return render(request, 'membres/listmembres.html', {'members': members})
    except Exception as e:
        logger.error(f"Erreur lors de la récupération des membres : {e}", exc_info=True)
        messages.error(request, "Erreur lors du chargement des membres.")
        return redirect('app_bibliothecaire:home_bibliothecaire')


def addmember(request):
    """ Gère l'ajout d'un nouveau membre.

        Affiche un formulaire d'ajout de membre. Si la requête est une soumission de formulaire (POST),
        elle valide les données et enregistre un nouveau membre dans la base de données. En cas d'erreur, un message
        d'erreur est affiché. Si la méthode est GET, un formulaire vide est affiché pour que l'utilisateur puisse saisir
        les informations du membre.

        Args:
            request (HttpRequest): L'objet requête HTTP.

        Returns:
            HttpResponse: La réponse contenant le rendu du formulaire d'ajout de membre ou une redirection vers la liste des membres
                          en cas de succès ou d'erreur.
        """
    logger.info("Soumission du formulaire d'ajout de membre.")
    if request.method == 'POST':
        membercreation = Membercreation(request.POST)
        if membercreation.is_valid():
            try:
                member = Member()
                member.name = membercreation.cleaned_data['name']
                member.first_name = membercreation.cleaned_data['first_name']
                member.email = membercreation.cleaned_data['email']
                member.phone = membercreation.cleaned_data['phone']
                member.save()
                logger.info(f"Membre ajouté avec succès : {member.name} {member.first_name}")
                messages.success(request, "Le membre a été mis ajouté avec succès !")
                return redirect('app_bibliothecaire:listmembres')
            except Exception as e:
                logger.error(f"Erreur lors de l'ajout du membre : {e}", exc_info=True)
                messages.error(request, "Erreur lors de l'ajout du membre.")
        else:
            logger.warning("Formulaire d'ajout de membre invalide.")
            return render(request, 'membres/ajoutmembre.html', {'memberCreation': membercreation})
    else:
        logger.info("Affichage de la page d'ajout de membre.")
        membercreation = Membercreation()
        return render(request, 'membres/ajoutmembre.html', {'memberCreation': membercreation})


def memberupdate(request, id):
    """ Permet de mettre à jour les informations d'un membre.

    Paramètres :
        - request (HttpRequest) : La requête HTTP.
        - id (int) : L'ID du membre à mettre à jour.

    Retour :
        - HttpResponse : La page du formulaire de mise à jour ou une redirection après mise à jour réussie.
    """
    member = get_object_or_404(Member, pk=id)
    if request.method == 'POST':
        member_update = Memberupdate(request.POST)
        if member_update.is_valid():
            member.name = member_update.cleaned_data['name']
            member.first_name = member_update.cleaned_data['first_name']
            member.email = member_update.cleaned_data['email']
            member.phone = member_update.cleaned_data['phone']
            member.save()
            messages.success(request, "Le membre a été mis à jour avec succès !")
        return redirect('app_bibliothecaire:listmembres')
    else:
        member_update = Memberupdate(initial={
            'name': member.name,
            'first_name': member.first_name,
            'email': member.email,
            'phone': member.phone,
        })
    return render(request, 'membres/updatemembre.html', {'memberupdate': member_update})


def memberdelete(request, id):
    """ Permet de supprimer un membre de la bibliothèque.

    Paramètres :
        - request (HttpRequest) : La requête HTTP.
        - id (int) : L'ID du membre à supprimer.

    Retour :
        - HttpResponseRedirect : Redirection vers la liste des membres après suppression.
    """
    logger.info(f"Tentative de suppression du membre avec ID : {id}")
    try:
        member = get_object_or_404(Member, pk=id)
        member.delete()
        logger.info(f"Membre supprimé avec succès : {member.name} {member.first_name}")
        messages.success(request, "Le membre a été supprimé avec succès !")
    except Exception as e:
        logger.error(f"Erreur lors de la suppression du membre : {e}", exc_info=True)
        messages.error(request, "Erreur lors de la suppression du membre.")
    return redirect('app_bibliothecaire:listmembres')


# Fonctionnalités : Média
def listmedia(request):
    logger.info("Accès à la liste des médias.")
    try:
        books = Book.objects.all()
        dvds = Dvd.objects.all()
        cds = Cd.objects.all()
        boards = Board.objects.all()

        for book in books:
            book.current_loans = book.loans.filter(effective_return_date__isnull=True).first()
        for dvd in dvds:
            dvd.current_loans = dvd.loans.filter(effective_return_date__isnull=True).first()
        for cd in cds:
            cd.current_loans = cd.loans.filter(effective_return_date__isnull=True).first()

        context = {
            'books': books,
            'dvds': dvds,
            'cds': cds,
            'boards': boards,
        }
        logger.debug(f"Médias récupérés : {len(books)} livres, {len(dvds)} DVD, {len(cds)} CD, {len(boards)} plateaux.")
        return render(request, 'media/listmedia.html', context)
    except Exception as e:
        logger.error(f"Erreur lors de la récupération des médias : {e}", exc_info=True)
        messages.error(request, "Erreur lors du chargement des médias.")
        return redirect('app_bibliothecaire:home_bibliothecaire')


def addmedia(request):
    return render(request, 'media/ajoutmedia.html')


def add_book(request):
    if request.method == 'POST':
        bookform = BookForm(request.POST)
        if bookform.is_valid():
            book = Book()
            book.name = bookform.cleaned_data['name']
            book.author = bookform.cleaned_data['author']
            book.availability = bookform.cleaned_data['availability']
            book.nb_pages = bookform.cleaned_data['nb_pages']
            book.category = bookform.cleaned_data['categorie']
            book.save()
            messages.success(request, "Le livre a été ajouté à la liste des médias avec succès !")
            return redirect('app_bibliothecaire:ajoutmedia')
        else:
            return render(request, 'media/ajout_livre.html', {'bookForm': bookform})
    else:
        bookform = BookForm()
        return render(request, 'media/ajout_livre.html', {'bookForm': bookform})


def add_dvd(request):
    if request.method == 'POST':
        dvdform = DvdForm(request.POST)
        if dvdform.is_valid():
            dvd = Dvd()
            dvd.name = dvdform.cleaned_data['name']
            dvd.author = dvdform.cleaned_data['author']
            dvd.availability = dvdform.cleaned_data['availability']
            dvd.genre = dvdform.cleaned_data['genre']
            dvd.category = dvdform.cleaned_data['categorie']
            dvd.save()
            messages.success(request, "Le DVD a été ajouté à la liste des médias avec succès !")
            return redirect('app_bibliothecaire:ajoutmedia')
        else:
            return render(request, 'media/ajout_dvd.html', {'dvdForm': dvdform})
    else:
        dvdform = DvdForm()
        return render(request, 'media/ajout_dvd.html', {'dvdForm': dvdform})


def add_cd(request):
    if request.method == 'POST':
        cdform = CdForm(request.POST)
        if cdform.is_valid():
            cd = Cd()
            cd.name = cdform.cleaned_data['name']
            cd.author = cdform.cleaned_data['author']
            cd.availability = cdform.cleaned_data['availability']
            cd.release_date = cdform.cleaned_data['release_date']
            cd.category = cdform.cleaned_data['categorie']
            cd.save()
            messages.success(request, "Le CD a été ajouté à la liste des médias avec succès !")
            return redirect('app_bibliothecaire:ajoutmedia')
        else:

app_bibliothecaire/templates/media/ajout_cd.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Ajouter un CD</title>
</head>
<body>
  <h2>Ajouter un CD</h2>
  <form method="post">
        {% csrf_token %}
        {{ cdForm.as_p }}
        <button type="submit">Ajouter le CD</button>
  </form><br>
  <a href="{% url 'app_bibliothecaire:ajoutmedia' %}">Retour</a>
</body>
</html>

app_bibliothecaire/templates/media/ajout_dvd.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>ajouter un DVD</title>
</head>
<body>
    <h2>Ajouter un DVD</h2>

    <form method="post">
        {% csrf_token %}
        {{ dvdForm.as_p }}
        <button type="submit">Ajouter le DVD</button>
    </form><br>

    <a href="{% url 'app_bibliothecaire:ajoutmedia' %}">Retour</a>
</body>
</html>

app_bibliothecaire/templates/media/ajout_livre.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Ajouter un livre</title>
</head>
<body>
  <h2>Ajouter un Livre</h2>
  <form method="post">
        {% csrf_token %}
        {{ bookForm.as_p }}
        <button type="submit">Ajouter le Livre</button>
  </form><br>
  <a href="{% url 'app_bibliothecaire:ajoutmedia' %}">Retour</a>
</body>
</html>

app_bibliothecaire/templates/media/ajout_plateau.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Ajouter un Plateau de Jeux</title>
</head>
<body>
  <h2>Ajouter un Plateau de Jeux</h2>
  <form method="post">
        {% csrf_token %}
        {{ boardForm.as_p }}
        <button type="submit">Ajouter le plateau de jeux</button>
  </form><br>
  <a href="{% url 'app_bibliothecaire:ajoutmedia' %}">Retour</a>
</body>
</html>

app_bibliothecaire/templates/media/ajoutmedia.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Ajout Media</title>
    <style>
        .message {
            position: fixed;
            top: 10px;
            right: 10px;
            background-color: #4CAF50; /* Vert pour succès */
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            font-size: 14px;
            z-index: 1000; /* Pour que ça soit au-dessus d'autres éléments */
        }
    </style>
</head>
<body>
    <button>
      <a href="{% url 'app_bibliothecaire:home_bibliothecaire' %}">Retour au menu</a>
    </button>
    <button>
      <a href="{% url 'app_bibliothecaire:listmedia' %}">Liste des médias</a>
    </button>

    <h2>Ajoutez un média !</h2>

     {% if messages %}
        <div class="message">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <p>Choisissez le type de média que vous souhaitez ajouter :</p>
    <ul>
        <li><a href="{% url 'app_bibliothecaire:ajout_livre' %}">Ajouter un Livre</a></li>
        <li><a href="{% url 'app_bibliothecaire:ajout_dvd' %}">Ajouter un DVD</a></li>
        <li><a href="{% url 'app_bibliothecaire:ajout_cd' %}">Ajouter un CD</a></li>
        <li><a href="{% url 'app_bibliothecaire:ajout_plateau' %}">Ajouter un Plateau de Jeux</a></li>
    </ul>

</body>
</html>

app_bibliothecaire/templates/media/listmedia.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Liste Medias</title>
</head>
<body>
    <a href="{% url 'app_bibliothecaire:home_bibliothecaire' %}">Retour au menu</a>
    <h1>Liste des Médias</h1>

    <h2>Livres</h2>
    <ul>
        {% for book in books %}
        <li>
          <p>Titre : {{ book.name }}</p>
          <p>Auteur : {{ book.author }}</p>
          <p>Nombre de pages : {{ book.nb_pages }}</p>
          {% if book.current_loans %}
            <p>Emprunté par {{ book.current_loans.borrower.name }}
                {{ book.current_loans.borrower.first_name }}
                le {{ book.current_loans.loan_date|date:"d/m/Y" }}</p>
            <p>Date de retour prévue avant le {{ book.current_loans.expected_return_date|date:"d/m/Y" }}</p>
          {% else %}
            <p>Disponible à l'emprunt</p>
          {% endif %}
          <form action="{% url 'app_bibliothecaire:deletemedia' id=book.id %}" method="POST" style="display:inline;">
                {% csrf_token %}
                <button type="submit">Supprimer</button>
          </form>
      </li><br>
      {% endfor %}
    </ul>

    <h2>DVD</h2>
    <ul>
        {% for dvd in dvds %}
        <li>
          <p>Titre : {{ dvd.name }}</p>
          <p>Réalisateur : {{ dvd.author }}</p>
          <p>Genre : {{ dvd.genre }}</p>
          {% if dvd.current_loans %}
            <p>Emprunté par {{ dvd.current_loans.borrower.name }}
                {{ dvd.current_loans.boorower.first_name }}
                le {{ dvd.current_loans.loan_date|date:"d/m/Y" }}</p>
            <p>Date de retour prévue avant le {{ dvd.current_loans.expected_return_date|date:"d/m/Y" }}</p>
          {% else %}
            <p>Disponible à l'emprunt</p>
          {% endif %}
          <form action="{% url 'app_bibliothecaire:deletemedia' id=dvd.id %}" method="POST" style="display:inline;">
                {% csrf_token %}
                <button type="submit">Supprimer</button>
          </form>
      </li><br>
      {% endfor %}
    </ul>

    <h2>CD</h2>
    <ul>
        {% for cd in cds %}
        <li>
          <p>Titre : {{ cd.name }}</p>
          <p>Artiste : {{ cd.author }}</p>
          <p>Date de sortie : {{ cd.release_date }}</p>
          {% if cd.current_loans %}
            <p>Emprunté par {{ cd.current_loans.borrower.name }}
                {{ cd.current_loans.borrower.first_name }}
                le {{ cd.current_loans.loan_date|date:"d/m/Y" }}</p>
            <p>Date de retour prévue avant le {{ cd.current_loans.expected_return_date|date:"d/m/Y" }}</p>
          {% else %}
            <p>Disponible à l'emprunt</p>
          {% endif %}
          <form action="{% url 'app_bibliothecaire:deletemedia' id=cd.id %}" method="POST" style="display:inline;">
                {% csrf_token %}
                <button type="submit">Supprimer</button>
          </form>
      </li><br>
      {% endfor %}
    </ul>

    <h2>Jeux de plateau</h2>
    <ul>
        {% for board in boards %}
        <li>
          <p>Nom du jeu : {{ board.name }}</p>
          <p>Créateur : {{ board.author }}</p>
          <p>Nombre de joueurs : de {{ board.number_players_min }} à {{ board.number_players_max}} joueurs</p>
          <p style="color: red; font-weight: bold;">Les jeux de plateaux ne sont pas disponibles à l'emprunt.</p>
          <form action="{% url 'app_bibliothecaire:deletemedia' id=board.id %}" method="POST" style="display:inline;">
                {% csrf_token %}
                <button type="submit">Supprimer</button>
          </form>
        </li><br>
      {% endfor %}
    </ul>
</body>
</html>